'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="database")>  _
Partial Public Class KategorieDataSourceDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub Insertprodukty(instance As produkty)
    End Sub
  Partial Private Sub Updateprodukty(instance As produkty)
    End Sub
  Partial Private Sub Deleteprodukty(instance As produkty)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("databaseConnectionString1").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property produkties() As System.Data.Linq.Table(Of produkty)
		Get
			Return Me.GetTable(Of produkty)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.produkty")>  _
Partial Public Class produkty
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _idProduktu As String
	
	Private _nazwa As String
	
	Private _cena As System.Nullable(Of Integer)
	
	Private _opis As String
	
	Private _data_dodania As System.Nullable(Of Date)
	
	Private _kategoria As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnidProduktuChanging(value As String)
    End Sub
    Partial Private Sub OnidProduktuChanged()
    End Sub
    Partial Private Sub OnnazwaChanging(value As String)
    End Sub
    Partial Private Sub OnnazwaChanged()
    End Sub
    Partial Private Sub OncenaChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OncenaChanged()
    End Sub
    Partial Private Sub OnopisChanging(value As String)
    End Sub
    Partial Private Sub OnopisChanged()
    End Sub
    Partial Private Sub Ondata_dodaniaChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub Ondata_dodaniaChanged()
    End Sub
    Partial Private Sub OnkategoriaChanging(value As String)
    End Sub
    Partial Private Sub OnkategoriaChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idProduktu", DbType:="VarChar(10) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property idProduktu() As String
		Get
			Return Me._idProduktu
		End Get
		Set
			If (String.Equals(Me._idProduktu, value) = false) Then
				Me.OnidProduktuChanging(value)
				Me.SendPropertyChanging
				Me._idProduktu = value
				Me.SendPropertyChanged("idProduktu")
				Me.OnidProduktuChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nazwa", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property nazwa() As String
		Get
			Return Me._nazwa
		End Get
		Set
			If (String.Equals(Me._nazwa, value) = false) Then
				Me.OnnazwaChanging(value)
				Me.SendPropertyChanging
				Me._nazwa = value
				Me.SendPropertyChanged("nazwa")
				Me.OnnazwaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cena", DbType:="Int")>  _
	Public Property cena() As System.Nullable(Of Integer)
		Get
			Return Me._cena
		End Get
		Set
			If (Me._cena.Equals(value) = false) Then
				Me.OncenaChanging(value)
				Me.SendPropertyChanging
				Me._cena = value
				Me.SendPropertyChanged("cena")
				Me.OncenaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_opis", DbType:="VarChar(MAX)")>  _
	Public Property opis() As String
		Get
			Return Me._opis
		End Get
		Set
			If (String.Equals(Me._opis, value) = false) Then
				Me.OnopisChanging(value)
				Me.SendPropertyChanging
				Me._opis = value
				Me.SendPropertyChanged("opis")
				Me.OnopisChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_data_dodania", DbType:="Date")>  _
	Public Property data_dodania() As System.Nullable(Of Date)
		Get
			Return Me._data_dodania
		End Get
		Set
			If (Me._data_dodania.Equals(value) = false) Then
				Me.Ondata_dodaniaChanging(value)
				Me.SendPropertyChanging
				Me._data_dodania = value
				Me.SendPropertyChanged("data_dodania")
				Me.Ondata_dodaniaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_kategoria", DbType:="VarChar(10)")>  _
	Public Property kategoria() As String
		Get
			Return Me._kategoria
		End Get
		Set
			If (String.Equals(Me._kategoria, value) = false) Then
				Me.OnkategoriaChanging(value)
				Me.SendPropertyChanging
				Me._kategoria = value
				Me.SendPropertyChanged("kategoria")
				Me.OnkategoriaChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
